# Generated by Django 5.0.6 on 2024-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('party_size', models.IntegerField()),
            ],
            options={
                'permissions': [('customer_data', 'Can access customer data'), ('trend_analysis', 'Can access the trend analysis'), ('generate_report', 'Can generate reports')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('update_menu', 'Can update the menu')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/restaurant_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'permissions': [('update_photo', 'Can update the photo')],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=100)),
                ('next_available_reservation', models.DateTimeField()),
            ],
            options={
                'permissions': [('owner_dashboard', 'Can access the owner dashboard'), ('create_restaurant', 'Can add restaurants'), ('update_restaurant', 'Can update restaurants')],
            },
        ),
    ]
