# Generated by Django 5.0.6 on 2024-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_foodtype_restaurant_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='restaurants/restaurant_photos/'),
        ),
    ]
