# Generated by Django 5.0.6 on 2024-06-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('marketung', 'Marketing')], default='customer', max_length=10),
        ),
    ]
