# Generated by Django 5.0.6 on 2024-06-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('profile_view', 'Can view profiles')]},
        ),
    ]
