# Generated by Django 5.0.6 on 2024-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('RestaurantManager', 'Restaurant Manager'), ('Marketing', 'Marketing'), ('Staff', 'Staff')], default='Customer', max_length=25),
        ),
    ]
