# Generated by Django 5.0.6 on 2024-06-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_specialoffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'permissions': [('dish_create', 'Can create dishes'), ('dish_edit', 'Can edit dishes')]},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('get_notifications', 'Can get notifications'), ('clear_notifications', 'Can clear notifications')]},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'permissions': [('promotion_create', 'Can create promotions'), ('promotion_edit', 'Can edit promotions')]},
        ),
        migrations.AlterModelOptions(
            name='specialoffer',
            options={'permissions': [('special_offer', 'Can create special offers')]},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': [('table_list', 'Can access table lists'), ('change_status', 'Can change the table status'), ('seat_plan', 'Can access the seat plan')]},
        ),
    ]
