# Generated by Django 5.0.6 on 2024-06-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('table_seating_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('guest_count', models.IntegerField()),
                ('special_requests', models.TextField()),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table_seating_management.table')),
            ],
        ),
    ]
