# Generated by Django 5.0.6 on 2024-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('f', 'Frei'), ('r', 'Reserviert'), ('b ', 'Außer Betrieb')], max_length=15)),
            ],
        ),
    ]
