# Generated by Django 5.0.6 on 2024-06-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_seating_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Frei', 'Frei'), ('Reserviert', 'Reserviert'), ('Außer Betrieb', 'Außer Betrieb')], max_length=15),
        ),
    ]
