# Generated by Django 5.0.6 on 2024-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'permissions': [('view_reservationlist', 'Can view the list of reservations'), ('view_reservationdetail', 'Can view the detail of a reservation'), ('change_reservation', 'Can edit reservations'), ('add_reservation', 'Can add reservations'), ('delete_reservation', 'Can delete reservations')],
            },
        ),
    ]
