# Generated by Django 5.0.6 on 2024-06-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
        ('reservations', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.table'),
        ),
    ]
