# Generated by Django 5.0.6 on 2024-06-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservations_special_requests_reservations_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'permissions': [('view_reservationlist', 'Can view the list of reservations'), ('view_reservationdetail', 'Can view the detail of a reservation'), ('change_reservation', 'Can edit reservations'), ('add_reservation', 'Can add reservations'), ('delete_reservation', 'Can delete reservations')]},
        ),
    ]
