# Generated by Django 5.0.4 on 2024-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('next_available_reservation', models.DateTimeField()),
            ],
        ),
    ]
