# Generated by Django 5.0.6 on 2024-06-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
