# Generated by Django 5.0.6 on 2024-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_management', '0002_loyaltyprogram_rename_name_promotion_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('points_required', models.IntegerField(verbose_name='Erforderliche Treuepunkte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
            ],
        ),
        migrations.DeleteModel(
            name='LoyaltyProgram',
        ),
        migrations.AddField(
            model_name='promotion',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Treuepunkte'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='special_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spezialmenüartikel'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Rabatt'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titel'),
        ),
    ]
